GET https://localhost:5127/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MmI0ZmExYy1jYjFjLTRjMDAtOWM0MS05MzAyMDFkYzg2MTAiLCJnaXZlbl9uYW1lIjoiQW5kcmV3IiwiZmFtaWx5X25hbWUiOiJQZXJleiIsImp0aSI6ImFiY2RkYzY3LTU5MzUtNDVlOS1hNzA0LWRjMTYzMTg1OTY0OSIsImV4cCI6MTY3MzczMDYwOSwiaXNzIjoiQnViYmVyRGlubmVyIiwiYXVkIjoiQnViYmVyRGlubmVyIn0.DSKv3EiVtOzyX58JXLo1aPMqmkqIrTwhmJ5blzj_9gg